export interface Credit {
  role: string;
  name: string;
}

export interface Project {
  slug: string;
  title: string;
  client: string;
  category: string;
  categoryColor: string;
  format: string;
  year: number;
  thumb: string;
  thumb2?: string;
  videoUrl?: string;
  videoVertical?: boolean;
  logline: string;
  description: string;
  tags: string[];
  role?: string;
  credits?: Credit[];
  quote?: string;
  quoteBy?: string;
  preview?: string;
  template?: 'feature' | 'vertical' | 'mosaic' | 'gallery' | 'gallery-mixed' | 'content' | 'multi-video' | 'multiregion';
  media?: Array<{ type: 'image' | 'video'; src: string; span?: number }>;
  videos?: string[];
  productionCompany?: string;
  countries?: Array<{ name: string; image?: string }>;
  formatLabel?: string;
  watchUrl?: string;
  watchLabel?: string;
  featured?: boolean;
  images?: string[];
  reels?: string[];
  eventOnly?: boolean;
  shortTitle?: string;
  gridCols?: number;
  categories?: string[];
}

export const CATEGORY_COLORS: Record<string, string> = {
  Motorsport: '#FF3B30',
  Film: '#FF9F0A',
  Documentary: '#30D158',
  AI: '#BF5AF2',
  Events: '#FFD60A',
  Content: '#FF375F',
};

export const projects: Project[] = [

  // ─── PROYECTOS REALES ────────────────────────────────────────────────

  {
    slug: 'dazn-scalpers',
    title: 'Roadtrip',
    client: 'DAZN × Scalpers',
    category: 'Motorsport',
    categoryColor: CATEGORY_COLORS['Motorsport'],
    format: 'TV',
    year: 2026,
    thumb: '/projects/dazn-scalpers/thumb.png',
    thumb2: '/projects/dazn-scalpers/thumb2.png',
    role: 'Production Company',
    watchUrl: 'https://www.dazn.com/es-ES/home/ArticleId:bs24kzqdrozc1gtti9mws866h/bs24kzqdrozc1gtti9mws866h',
    watchLabel: 'Watch on DAZN',
    logline: 'Pol Espargaró and Antonio Lobato. A road trip, a fragrance, a conversation.',
    description: 'Two icons of Spanish motorsport, a classic Mustang, and a mountain road that did most of the talking. A TV campaign built around chemistry — not a script.',
    tags: ['Publicidad', 'TV', 'Sport'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'DoP', name: 'Joan Hernández' },
      { role: 'AC', name: 'Georgina Cercós' },
      { role: 'Runner', name: 'Manuel Cortés' },
      { role: 'Edit', name: 'LOOOK' },
      { role: 'Sound', name: 'Pau López' },
      { role: 'Talents', name: 'Pol Espargaró y Antonio Lobato' },
      { role: 'Car Rental', name: 'Tyreaction' },
      { role: 'Thanks', name: 'Masia Solior · Café Joan' },
    ],
    template: 'gallery',
    images: [
      '/projects/dazn-scalpers/still-01.png',
      '/projects/dazn-scalpers/still-02.png',
      '/projects/dazn-scalpers/still-03.png',
      '/projects/dazn-scalpers/still-04.png',
      '/projects/dazn-scalpers/still-05.png',
      '/projects/dazn-scalpers/still-06.png',
      '/projects/dazn-scalpers/still-07.png',
      '/projects/dazn-scalpers/still-08.png',
      '/projects/dazn-scalpers/still-09.png',
    ],
    featured: true,
  },

  {
    slug: 'usc-heroes-jonan',
    title: 'Heroes — Jonan Wiergo',
    client: 'Urban Sports Club',
    category: 'Documentary',
    categoryColor: CATEGORY_COLORS['Documentary'],
    format: 'DOCUMENTARY',
    year: 2024,
    thumb: '/projects/usc-heroes-jonan/thumb.png',
    thumb2: '/projects/usc-heroes-jonan/thumb2.png',
    preview: '/projects/usc-heroes-jonan/preview.mp4',
    role: 'Production Company',
    videoUrl: 'https://www.youtube.com/watch?v=shr2YM4pI-k',
    logline: 'Movement, community, and what it means to be an everyday hero.',
    description: 'Documentary portrait of Jonan Wiergo for the Heroes series. An intimate look at what drives the people who move others — filmed across his world: the gym, the street, the quiet moments in between.',
    tags: ['Documental', 'Sport', 'Social'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'DoP', name: 'Joan Hernández' },
      { role: 'AC', name: 'Georgina Cercós' },
      { role: 'Make Up', name: 'Naiara Olalde' },
      { role: 'Edit', name: 'LOOOK' },
      { role: 'Sound Design', name: 'PGSound' },
      { role: 'Talent', name: 'Jonan Wiergo' },
      { role: 'Thanks', name: 'Guakame · La Huella Workout Club · Goodfit Studio' },
    ],
    template: 'feature',
    featured: true,
  },

  {
    slug: 'usc-heroes-liana',
    title: 'Heroes — Liana Grieg',
    client: 'Urban Sports Club',
    category: 'Documentary',
    categoryColor: CATEGORY_COLORS['Documentary'],
    format: 'DOCUMENTARY',
    year: 2024,
    thumb: '/projects/usc-heroes-liana/thumb.png',
    thumb2: '/projects/usc-heroes-liana/thumb2.png',
    role: 'Production Company',
    videoUrl: 'https://www.youtube.com/watch?v=JlrZ9kemzfs',
    logline: 'Strength, rhythm, and the quiet discipline that never makes the highlight reel.',
    description: 'Documentary portrait of Liana Grieg for the Heroes series. The training that happens before anyone is watching — and the mindset that makes it worth it.',
    tags: ['Documental', 'Sport', 'Social'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'DoP', name: 'Joan Hernández' },
      { role: 'AC', name: 'Georgina Cercós' },
      { role: 'Make Up', name: 'Naiara Olalde' },
      { role: 'Edit', name: 'LOOOK' },
      { role: 'Sound Design', name: 'PGSound' },
      { role: 'Talent', name: 'Liana Grieg' },
      { role: 'Thanks', name: 'Guakame · La Huella Workout Club · Goodfit Studio' },
    ],
    template: 'feature',
    featured: true,
  },

  {
    slug: 'usc-drone-cities',
    title: 'Signal',
    client: 'Urban Sports Club',
    category: 'AI',
    categoryColor: CATEGORY_COLORS['AI'],
    categories: ['AI', 'Content'],
    format: 'AI',
    year: 2026,
    thumb: '/projects/usc-drone-cities/thumb.jpg',
    role: 'Production Company',
    logline: 'Eight European cities seen from a perspective that doesn\'t exist yet.',
    description: 'Eight vertical films generated with Seedance AI — each one a European city shot through an impossible aerial lens. Barcelona, Madrid, London, Berlin, Amsterdam, Lisbon, Rome, Paris.',
    tags: ['Video IA', 'Drone', 'AI'],
    template: 'vertical',
    images: [
      '/projects/usc-drone-cities/city-01.mp4',
      '/projects/usc-drone-cities/city-02.jpg',
      '/projects/usc-drone-cities/city-03.jpg',
      '/projects/usc-drone-cities/city-04.jpg',
    ],
  },

  {
    slug: 'dr-resin-live-sessions',
    title: 'DR.RESIN Live Sessions',
    client: 'DR.RESIN',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'MUSIC',
    formatLabel: 'LIVE SESSIONS',
    year: 2025,
    thumb: '/projects/dr-resin-live-sessions/thumb.png',
    watchUrl: 'https://www.youtube.com/@DrResinLiveSessions/videos',
    watchLabel: 'Watch on YouTube',
    logline: 'A musical utopia in Barcelona — captured live, released worldwide.',
    description: 'DR.RESIN Social Club is where artists come to play for real. Every month, a musician steps into the room, the crowd fills in, and something happens that can\'t be rehearsed. Over 100 episodes of that energy — recorded, edited, and sent out into the world.',
    tags: ['Music', 'Live', 'Session'],
    credits: [
      { role: 'Director', name: 'Joan Hernández & Sergi Gómez' },
      { role: 'Film', name: 'Joan Hernández, Georgina Cercós, Sergi Gómez' },
      { role: 'Live Recording', name: 'Rafael Giner' },
      { role: 'Art Direction', name: 'Federica Encinoza & Estibalitz Girón' },
      { role: 'Audio Mastering', name: 'Rafael Giner' },
      { role: 'Logo Design', name: 'Le Maritime Studio' },
      { role: 'Subtítulos', name: 'C E Blanco' },
      { role: 'Production', name: 'Federica Encinoza & Estibalitz Girón' },
      { role: 'Thanks', name: 'Dr. Resin Social Club' },
    ],
    template: 'content',
    media: [
      { type: 'image', src: '/projects/dr-resin-live-sessions/still-01.png' },
      { type: 'image', src: '/projects/dr-resin-live-sessions/still-02.png' },
      { type: 'video', src: '/projects/dr-resin-live-sessions/clip-01.mp4' },
      { type: 'video', src: '/projects/dr-resin-live-sessions/clip-02.mp4' },
      { type: 'image', src: '/projects/dr-resin-live-sessions/still-03.png' },
      { type: 'image', src: '/projects/dr-resin-live-sessions/still-04.png' },
      { type: 'image', src: '/projects/dr-resin-live-sessions/still-05.png' },
      { type: 'video', src: '/projects/dr-resin-live-sessions/clip-03.mp4' },
      { type: 'image', src: '/projects/dr-resin-live-sessions/still-06.png' },
    ],
    featured: true,
  },

  {
    slug: 'vilas-del-jaro',
    title: 'Viñas del Jaro',
    client: 'Viñas del Jaro',
    category: 'Content',
    categoryColor: CATEGORY_COLORS['Content'],
    format: 'CONTENT',
    year: 2024,
    thumb: '/projects/vilas-del-jaro/thumb.png',
    role: 'Production Company',
    logline: 'A place. A light. The camera that found it.',
    description: 'Photography and video for Viñas del Jaro winery. Landscape, architecture, and the quiet ritual of wine — from ground level and from the air. A place that earns its image without trying.',
    tags: ['Content', 'Photography', 'Drone'],
    credits: [
      { role: 'Director / Fotografía / Drone', name: 'Sergi Gómez' },
      { role: 'DoP', name: 'Fer Taranco' },
      { role: 'Agency', name: 'Wardem' },
    ],
    template: 'content',
    media: [
      { type: 'image', src: '/projects/vilas-del-jaro/still-01.png' },
      { type: 'image', src: '/projects/vilas-del-jaro/still-02.png' },
      { type: 'video', src: '/projects/vilas-del-jaro/clip-01.mp4' },
      { type: 'video', src: '/projects/vilas-del-jaro/clip-02.mp4' },
      { type: 'image', src: '/projects/vilas-del-jaro/still-03.png' },
      { type: 'image', src: '/projects/vilas-del-jaro/still-04.png' },
      { type: 'image', src: '/projects/vilas-del-jaro/still-05.png' },
      { type: 'image', src: '/projects/vilas-del-jaro/still-06.png' },
      { type: 'video', src: '/projects/vilas-del-jaro/clip-03.mp4' },
      { type: 'image', src: '/projects/vilas-del-jaro/still-07.png' },
      { type: 'video', src: '/projects/vilas-del-jaro/clip-04.mp4' },
      { type: 'image', src: '/projects/vilas-del-jaro/still-08.png' },
    ],
  },

  {
    slug: 'gearing-up-suzuki',
    title: 'Gearing Up',
    client: 'Suzuki MotoGP',
    category: 'Motorsport',
    categoryColor: CATEGORY_COLORS['Motorsport'],
    format: 'FILM',
    year: 2022,
    thumb: '/projects/gearing-up-suzuki/thumb.png',
    preview: '/projects/gearing-up-suzuki/preview.mp4',
    role: 'Production Company',
    videoUrl: 'https://www.youtube.com/watch?v=yRYh3O3LEME',
    logline: 'The start of a season, told from the inside.',
    description: 'Season launch film for Suzuki MotoGP. Archive, on-track footage, and a voiceover that let the moments carry the weight. A film about what it feels like before the first race — before anything is decided.',
    tags: ['Motorsport', 'Racing', 'Film'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'Edit', name: 'Kruman & Sergi Gómez' },
      { role: 'Sound Design', name: 'Pau López' },
      { role: 'Voice Over', name: 'Tim McCaffrey' },
      { role: 'Additional Footage', name: 'Dorna' },
      { role: 'Photographs', name: 'Gigi Soldano & Alex Farinelli' },
    ],
    template: 'feature',
  },

  {
    slug: 'la-huella',
    title: 'La Huella',
    client: 'PGR Rugby',
    category: 'Documentary',
    categoryColor: CATEGORY_COLORS['Documentary'],
    format: 'DOCUMENTARY',
    year: 2020,
    thumb: '/projects/la-huella/thumb.png',
    thumb2: '/projects/la-huella/thumb2.png',
    role: 'DoP',
    videoUrl: 'https://www.youtube.com/watch?v=QC5YY1oj0KI',
    logline: 'Rugby, Chile, and the mark you leave when you play for real.',
    description: 'Documentary shot in Chile following PGR Rugby. A portrait of the game beyond the scoreboard — the culture, the mud, and the people who show up even when nobody\'s watching.',
    tags: ['Documental', 'Sport', 'Film'],
    credits: [
      { role: 'Director', name: 'Aljaz Babnik' },
      { role: 'Cinematographer', name: 'Sergi Gómez' },
      { role: 'Edit', name: 'Aljaz Babnik' },
      { role: 'Sound Design', name: 'Blaz Babnik' },
      { role: 'Producer', name: 'Pepe Serrano' },
      { role: 'Production', name: 'PGR Rugby' },
    ],
    template: 'feature',
    images: [
      '/projects/la-huella/still-01.png',
      '/projects/la-huella/still-02.png',
      '/projects/la-huella/still-03.png',
    ],
  },

  {
    slug: 'alex-rins-vuelve-a-casa',
    title: 'Vuelve a Casa',
    client: 'DAZN',
    category: 'Motorsport',
    categoryColor: CATEGORY_COLORS['Motorsport'],
    format: 'TV',
    year: 2024,
    thumb: '/projects/alex-rins-vuelve-a-casa/thumb.png',
    thumb2: '/projects/alex-rins-vuelve-a-casa/thumb2.png',
    role: 'Production Company',
    logline: 'Alex Rins. The comeback nobody saw coming.',
    description: 'TV film for DAZN built around one of the most unexpected returns in Spanish motorsport. Shot at Motorland Aragón — his home track, his story.',
    tags: ['Motorsport', 'TV', 'Sport'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'DoP', name: 'Joan Hernández' },
      { role: 'AD/AC', name: 'Oscar Criado' },
      { role: 'Runner', name: 'Georgina Cercós' },
      { role: 'Talents', name: 'Alex Rins, Amanda Gala' },
      { role: 'Thanks', name: 'Turismo Aragón · Motorland Aragón' },
    ],
    template: 'gallery',
    images: [
      '/projects/alex-rins-vuelve-a-casa/still-01.png',
      '/projects/alex-rins-vuelve-a-casa/still-02.png',
      '/projects/alex-rins-vuelve-a-casa/still-03.png',
      '/projects/alex-rins-vuelve-a-casa/still-04.png',
      '/projects/alex-rins-vuelve-a-casa/still-05.png',
      '/projects/alex-rins-vuelve-a-casa/still-06.png',
      '/projects/alex-rins-vuelve-a-casa/still-07.png',
      '/projects/alex-rins-vuelve-a-casa/still-08.png',
      '/projects/alex-rins-vuelve-a-casa/still-09.png',
    ],
  },

  {
    slug: 'fibritel',
    title: 'Fibritel',
    client: 'Fibritel',
    category: 'Motorsport',
    categoryColor: CATEGORY_COLORS['Motorsport'],
    format: 'FILM',
    year: 2026,
    thumb: '/projects/fibritel/thumb.png',
    videoUrl: 'https://www.youtube.com/watch?v=vU5GtxkOghY',
    role: 'Director',
    productionCompany: 'RestArts Studio',
    logline: 'Speed, technique, and the team behind the machine.',
    description: 'Film for Fibritel around the Momoven Moto2 team. Precision driving, aerials, and the kind of access that turns a sponsor piece into something cinematic.',
    tags: ['Motorsport', 'Racing', 'Film'],
    credits: [
      { role: 'Creative Direction', name: 'RestArts Studio' },
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'Camera', name: 'Aylor' },
      { role: 'Rig Tech', name: 'XXX' },
      { role: 'Precision Driver', name: 'Jaume Massagué' },
      { role: 'Drone', name: 'Alex Moles' },
      { role: 'Producer', name: 'Ivan' },
      { role: 'Edit', name: 'Aylor' },
      { role: 'Talent', name: 'Unai Orralde' },
      { role: 'Team', name: 'Momoven Moto2' },
      { role: 'Production Company', name: 'RestArts Studio' },
    ],
    template: 'feature',
  },

  {
    slug: 'malva',
    title: 'Malva',
    client: 'Malva',
    category: 'Content',
    categoryColor: CATEGORY_COLORS['Content'],
    format: 'PHOTOGRAPHY',
    year: 2022,
    thumb: '/projects/malva/thumb.png',
    logline: 'South Africa in Amsterdam. Bold flavours, warm light, and Dutch design.',
    description: 'Photography for Malva, a South African restaurant in Amsterdam. Where the warmth of the Cape meets the clean lines of the Netherlands — a space that feels like neither and both at once.',
    tags: ['Content', 'Photography', 'Food'],
    credits: [
      { role: 'Photography', name: 'Sergi Gómez' },
      { role: 'Marketing Manager', name: 'Estibalitz Girón' },
      { role: 'Creative Direction', name: 'Federica Encinoza' },
    ],
    template: 'gallery-mixed',
    images: [
      '/projects/malva/still-01.png', // H landscape
      '/projects/malva/still-02.png', // H landscape
      '/projects/malva/still-03.png', // V portrait
      '/projects/malva/still-04.png', // V portrait
      '/projects/malva/still-05.png', // H landscape
      '/projects/malva/still-06.png', // H landscape
      '/projects/malva/still-07.png', // H landscape
      '/projects/malva/still-08.png', // V portrait
      '/projects/malva/still-09.png', // H landscape
    ],
  },

  {
    slug: 'joventut-badalona',
    title: 'Presentació Temporada 25',
    client: 'Joventut de Badalona',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'FILM',
    year: 2024,
    thumb: '/projects/joventut-badalona/thumb.png',
    role: 'Production Company',
    logline: 'La Penya opens the season. One team. One statement.',
    description: 'Season presentation film for Joventut de Badalona 2025. Atmosphere, attitude, and the weight of a green-and-black badge that means something in this city. A film made for the people who don\'t need an explanation.',
    tags: ['Content', 'Sport', 'Film'],
    credits: [
      { role: 'Director', name: 'Joan Hernández' },
      { role: 'DoP', name: 'Sergi Gómez' },
      { role: 'Edit', name: 'Joan Hernández' },
    ],
    template: 'feature',
  },

  {
    slug: 'video-intelligente',
    title: 'Video Intelligence',
    client: 'Wardem',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'FILM',
    year: 2024,
    thumb: '/projects/video-intelligente/thumb.png',
    videoUrl: 'https://vimeo.com/1078008161/0d6ca56f72',
    role: 'Director',
    logline: 'Archive footage, AI imagery, and a new visual language for data.',
    description: 'Brand film for Wardem that makes data analytics feel like something — not charts, not dashboards. Archive and AI-generated visuals working together to explain what the platform actually does.',
    tags: ['Content', 'Film', 'AI'],
    credits: [
      { role: 'Creative Director', name: 'Julia Bajo' },
      { role: 'Film Director', name: 'Sergi Gómez' },
      { role: 'Edit & VFX', name: 'LOOOK Studio' },
      { role: 'Sound Design', name: 'PG Sound' },
      { role: 'Voice Over', name: 'Tamara Lozano' },
    ],
    template: 'feature',
  },

  {
    slug: 'somos-estupendas',
    title: 'Somos Visibles',
    client: 'Somos Estupendas',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'DOCUMENTARY',
    year: 2024,
    thumb: '/projects/somos-estupendas/thumb.png',
    role: 'Production Company',
    logline: 'Mental health. Real voices. The day we dare to speak.',
    description: 'Interview series for World Mental Health Day — people sharing what they don\'t usually share. Shot simply, with intention. The camera stayed out of the way.',
    tags: ['Documental', 'Social', 'Entrevista'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'Copy', name: 'Betsy Sabaté' },
      { role: 'DoP', name: 'Joan Hernández' },
      { role: 'Runner', name: 'Vanesa Miralles' },
      { role: 'Sound', name: 'Pau López' },
      { role: 'Edit', name: 'LOOOK' },
    ],
    template: 'gallery',
    images: [
      '/projects/somos-estupendas/still-01.png',
      '/projects/somos-estupendas/still-02.png',
      '/projects/somos-estupendas/still-03.png',
      '/projects/somos-estupendas/still-04.png',
      '/projects/somos-estupendas/still-05.png',
      '/projects/somos-estupendas/still-06.png',
      '/projects/somos-estupendas/still-07.png',
      '/projects/somos-estupendas/still-08.png',
      '/projects/somos-estupendas/still-09.png',
    ],
  },

  {
    slug: 'mega-mexico',
    title: 'Barcelona',
    client: 'Mega Mexico',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'FILM',
    year: 2022,
    thumb: '/projects/mega-mexico/thumb.png',
    role: 'Camera',
    logline: 'Ten Mexican creators. Barcelona. An ice cream brand. Lots of cameras.',
    description: 'Social content production for Mega Mexico — ten creators from Mexico, one city, one ice cream brand. Barcelona as the backdrop for content that needed to feel real and deliver fast. Multiple formats, parallel shoots, daily output.',
    tags: ['Content', 'Social', 'Influencers'],
    credits: [
      { role: 'Director', name: 'Juan Pablo Celis' },
      { role: 'DoP', name: 'Gil Arellano' },
      { role: 'Camera', name: 'Sergi Gómez' },
    ],
    template: 'multi-video',
    videos: [
      'https://vimeo.com/842341867/8d6049c4e1',
      'https://vimeo.com/842625675/55dc5cb792',
      'https://vimeo.com/842780514/e34263affe',
    ],
  },

  {
    slug: 'marmota-hay-que-dormir-mas',
    title: 'Hay que dormir más',
    client: 'Marmota',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'FILM',
    year: 2020,
    thumb: '/projects/marmota-hay-que-dormir-mas/thumb.png',
    preview: '/projects/marmota-hay-que-dormir-mas/preview.mp4',
    videoUrl: 'https://www.youtube.com/watch?v=M0-G3dG6UA8',
    role: 'Director',
    logline: 'A scientific study. 29 volunteers. The question we all avoid.',
    description: 'Case study film around the sleep research conducted by La Paz Hospital\'s Sleep Unit in Zaragoza. New mattresses, used ones, and 29 people who agreed to be observed. Part science, part social experiment.',
    tags: ['Documental', 'Film', 'Brand'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'DoP', name: 'Victor Catalá' },
      { role: '1AC', name: 'Jordi Marco' },
      { role: 'Sound', name: 'Pau López' },
      { role: 'Make Up', name: 'Naiara Olalde' },
      { role: 'Edit', name: 'Sergi Gómez' },
      { role: 'Sound Design', name: 'Sono XL' },
      { role: 'Producer', name: 'Alex Aguerri' },
      { role: 'Production Company', name: 'Lunartic Productions' },
    ],
    template: 'feature',
  },

  {
    slug: 'comtoyou-saudi',
    title: 'Comtoyou Racing',
    client: 'Saudi Motorsport',
    category: 'Motorsport',
    categoryColor: CATEGORY_COLORS['Motorsport'],
    format: 'FILM',
    year: 2025,
    thumb: '/projects/comtoyou-saudi/thumb.jpg',
    preview: '/projects/comtoyou-saudi/preview.mp4',
    role: 'Production Company',
    videoUrl: 'https://www.youtube.com/watch?v=3P0eQcof_F0',
    logline: 'A European racing team. The Saudi desert. Speed as a universal language.',
    description: 'A film for Comtoyou Racing, shot on location at the Saudi Motorsport Championship. Long straights, desert heat, and a Belgian team that felt completely at home. European precision, Middle Eastern scale.',
    tags: ['Motorsport', 'Racing', 'Film'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'DoP', name: 'Joan Hernández' },
      { role: 'Edit', name: 'LOOOK' },
    ],
    template: 'feature',
  },

  {
    slug: 'lust-affair',
    title: 'Lust Affair',
    client: 'Erika Lust',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2023,
    thumb: '/projects/lust-affair/thumb.png',
    role: 'Fotografía',
    logline: 'Cine Phenomena, Barcelona. A night to remember.',
    description: 'Photo coverage of Erika Lust\'s film premiere at Cine Phenomena. A space that doesn\'t take itself too seriously, and an audience that loves cinema for exactly what it is.',
    tags: ['Events', 'Photography'],
    template: 'gallery',
    images: [
      '/projects/lust-affair/still-01.png',
      '/projects/lust-affair/still-02.png',
      '/projects/lust-affair/still-03.png',
      '/projects/lust-affair/still-04.png',
      '/projects/lust-affair/still-05.png',
      '/projects/lust-affair/still-06.png',
      '/projects/lust-affair/still-07.png',
      '/projects/lust-affair/still-08.png',
      '/projects/lust-affair/still-09.png',
    ],
  },

  {
    slug: 'usc-talks',
    title: 'Talks',
    client: 'Urban Sports Club',
    category: 'Documentary',
    categoryColor: CATEGORY_COLORS['Documentary'],
    format: 'DOCUMENTARY',
    year: 2022,
    thumb: '/projects/usc-talks/thumb.png',
    role: 'Production Company',
    watchUrl: 'https://www.youtube.com/watch?v=raW_hWRhkZE&t=7s',
    watchLabel: 'Watch on YouTube',
    logline: 'Six conversations. The names redefining sport.',
    description: 'Interview series with some of the most influential voices in European sport and fitness — Conchi Bellorín, Sergi Balaguer, Chris Sharma, Dídac Font, Dídac Lee. Six episodes. No small talk.',
    tags: ['Documental', 'Sport', 'Entrevista'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'DoP', name: 'Toni Vidal' },
      { role: 'Sound', name: 'David Gascón' },
      { role: 'Make Up', name: 'Naiara Olalde & Ivan Carabaño' },
      { role: 'Diseño Gráfico', name: 'Digital Son Studio' },
      { role: 'Production Manager', name: 'Alex Aguerri' },
    ],
    template: 'gallery',
    images: [
      '/projects/usc-talks/still-01.png',
      '/projects/usc-talks/still-02.png',
      '/projects/usc-talks/still-03.png',
      '/projects/usc-talks/still-04.png',
      '/projects/usc-talks/still-05.png',
      '/projects/usc-talks/still-06.png',
      '/projects/usc-talks/still-07.png',
      '/projects/usc-talks/still-08.png',
      '/projects/usc-talks/still-09.png',
    ],
    featured: true,
  },

  {
    slug: 'oysho-adventure',
    title: 'Adventure',
    client: 'Oysho',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'FILM',
    year: 2024,
    thumb: '/projects/oysho-adventure/thumb.png',
    videoUrl: 'https://www.youtube.com/watch?v=9txfY0TGSR4',
    role: 'Camera',
    productionCompany: 'RestArts Studio',
    logline: 'Nature, movement, and the gear that goes with you when it matters most.',
    description: 'Campaign film for Oysho Adventure, shot on mountain terrain with natural light and no artificial warmth. A collection that had to keep up with the people wearing it — and did. Clean frames, honest movement.',
    tags: ['Publicidad', 'Fashion', 'Film'],
    credits: [
      { role: 'Director', name: 'Horacio Cabilla' },
      { role: 'DoP', name: 'Ari Oña' },
      { role: 'Camera', name: 'Sergi Gómez' },
      { role: 'BTS', name: 'Martí MDN' },
      { role: 'Photographer', name: 'Marc Sánchez' },
      { role: 'Production Manager', name: 'Leila' },
      { role: 'Production Assistant', name: 'Maria' },
      { role: 'Production Company', name: 'RestArts Studio' },
    ],
    template: 'feature',
  },

  {
    slug: 'bikkoa-manifest',
    title: 'Manifest',
    client: 'Bikkoa',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'FILM',
    year: 2024,
    thumb: '/projects/bikkoa-manifest/thumb.png',
    videoUrl: 'https://www.youtube.com/watch?v=0tsr18OTFpA',
    role: 'Camera & Edit',
    productionCompany: 'RestArts Studio',
    logline: 'A declaration. A brand. The image that says it all.',
    description: 'Manifesto film for Bikkoa — what this brand is, where it stands, and where it\'s going. A clear point of view shot with a team that shared it. The kind of brief that makes a crew show up early.',
    tags: ['Publicidad', 'Film', 'Brand'],
    credits: [
      { role: 'Director', name: 'Horacio Cabilla' },
      { role: 'Camera', name: 'Sergi Gómez' },
      { role: '1AC', name: 'Andy Zancan' },
      { role: '2AC', name: 'Victor Julian' },
      { role: 'BTS', name: 'Martí MDN' },
      { role: 'Runner', name: 'Pau Pérez' },
      { role: 'Photographer', name: 'Marc Sánchez' },
      { role: 'Edit', name: 'Sergi Gómez & Lucas Hope' },
      { role: 'Sound Design', name: 'Eli Ben Avi' },
      { role: 'Production Manager', name: 'Ester' },
      { role: 'Production Assistant', name: 'Valentina Nazatti' },
      { role: 'Make Up', name: 'Claudia' },
      { role: 'Gaffer', name: 'Gerard Alba' },
      { role: 'Spark', name: 'Jordi GH' },
      { role: 'Best Boy', name: 'Peitxp' },
      { role: 'Production Company', name: 'RestArts Studio' },
    ],
    template: 'feature',
  },

  {
    slug: 'usc-reels-2024',
    title: 'Reels',
    client: 'Urban Sports Club',
    category: 'Content',
    categoryColor: CATEGORY_COLORS['Content'],
    format: 'CONTENT',
    year: 2024,
    thumb: '/projects/usc-reels-2024/thumb.png',
    role: 'Production Company',
    logline: 'Vertical stories. One platform. Everything sport can be.',
    description: 'A series of reels for Urban Sports Club — each one built around what the platform actually offers its users. Sport as a lifestyle, not a routine. Shot to stop the scroll.',
    tags: ['Content', 'Reels', 'Social'],
    template: 'vertical',
    reels: [
      'C2zT2TUtsqk',
      'C2Hsjaltqag',
      'C5S6JpwtUeA',
      'DCmKPtCtT6r',
    ],
  },

  {
    slug: 'usc-ooh-2025',
    title: 'Out of Home',
    client: 'Urban Sports Club',
    category: 'AI',
    categoryColor: CATEGORY_COLORS['AI'],
    categories: ['AI', 'Content'],
    format: 'OOH',
    year: 2025,
    thumb: '/projects/usc-ooh-2025/thumb.png',
    thumb2: '/projects/usc-ooh-2025/thumb2.png',
    role: 'Production Company',
    logline: 'Eight cities. The brand on the street. AI made it possible.',
    description: 'Out of Home campaign for Urban Sports Club across eight European cities — Barcelona, Madrid, London, Berlin, Amsterdam, Lisbon, Rome, Paris. AI-generated poster visuals that brought the brand to the street at scale. Each city, its own light.',
    tags: ['OOH', 'AI', 'Content'],
    template: 'vertical',
    gridCols: 6,
    images: [
      '/projects/usc-ooh-2025/still-01.png',
      '/projects/usc-ooh-2025/still-02.png',
      '/projects/usc-ooh-2025/still-03.png',
      '/projects/usc-ooh-2025/still-04.png',
      '/projects/usc-ooh-2025/still-05.png',
      '/projects/usc-ooh-2025/still-06.png',
      '/projects/usc-ooh-2025/still-07.png',
      '/projects/usc-ooh-2025/still-08.png',
      '/projects/usc-ooh-2025/still-09.png',
      '/projects/usc-ooh-2025/still-10.png',
      '/projects/usc-ooh-2025/still-11.png',
      '/projects/usc-ooh-2025/still-12.png',
    ],
  },

  {
    slug: 'unicef-escola-amb-drets',
    title: 'Una escola amb drets',
    client: 'Unicef',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'FILM',
    year: 2020,
    thumb: '/projects/unicef-escola-amb-drets/thumb.png',
    videoUrl: 'https://www.youtube.com/watch?v=yonH48tedjk',
    role: 'Production Company',
    logline: 'A school. A set of rights. A story that needed to be told.',
    description: 'Film for Unicef\'s "Una escola amb drets" project — exploring how rights-based education changes the way children learn, speak, and see themselves.',
    tags: ['Documental', 'Social', 'Film'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'Art', name: 'Maria Palet' },
      { role: 'Edit', name: 'Sergi Gómez & Pablo Grau' },
      { role: 'Agency', name: 'Be Agency' },
    ],
    template: 'feature',
  },

  {
    slug: 'suzuki-thanks',
    title: 'Thanks',
    client: 'Suzuki MotoGP',
    category: 'Motorsport',
    categoryColor: CATEGORY_COLORS['Motorsport'],
    format: 'FILM',
    year: 2023,
    thumb: '/projects/suzuki-thanks/thumb.png',
    videoUrl: 'https://vimeo.com/801552238',
    role: 'Director',
    logline: 'Suzuki MotoGP\'s last goodbye.',
    description: 'Farewell film following Suzuki\'s withdrawal from the World Championship. A season of thanks — to the riders, the mechanics, and the fans who made it mean something.',
    tags: ['Motorsport', 'Film', 'Documental'],
    credits: [
      { role: 'Director', name: 'Sergi Gómez' },
      { role: 'Cameras', name: 'Joan Hernández, Oscar Criado' },
      { role: 'Edit', name: 'Sergi Gómez' },
      { role: 'Voice Over', name: 'Carol Jacobanis' },
      { role: 'Additional Footage', name: 'Suzuki, Dorna' },
      { role: 'Production Company', name: 'LOOOK' },
    ],
    template: 'feature',
  },

  {
    slug: 'usc-wellbeing-week',
    title: 'Wellbeing Week',
    client: 'Urban Sports Club',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'CONTENT',
    year: 2025,
    thumb: '/projects/usc-wellbeing-week/thumb.png',
    thumb2: '/projects/usc-wellbeing-week/thumb2.png',
    role: 'Production Company',
    videoUrl: 'https://www.youtube.com/watch?v=EZ2i9Ec26pI',
    logline: 'Four countries. Two weeks. 50+ pieces for social.',
    description: 'Parallel production across Spain, France, Portugal, and Amsterdam — local crews, coordinated in real time. 500 photographs, a global recap video, and daily deliveries that kept pace with the campaign.',
    tags: ['Content', 'Sport', 'Social'],
    template: 'multiregion',
    countries: [
      { name: 'Spain' },
      { name: 'Paris' },
      { name: 'Amsterdam' },
      { name: 'Lisboa' },
    ],
    images: [],
    credits: [
      { role: 'Director / Spain', name: 'Sergi Gómez' },
      { role: 'Edit Assistant', name: 'Georgina Cercós' },
      { role: 'Paris', name: 'Jean-Baptiste Dupont' },
      { role: 'AC Paris', name: 'Marie Lefebvre' },
      { role: 'Amsterdam', name: 'Lars van den Berg' },
      { role: 'Lisboa', name: 'Miguel Ferreira' },
    ],
  },

  {
    slug: 'hyrox-koln',
    title: 'Hyrox Köln',
    client: 'Urban Sports Club',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'CONTENT',
    year: 2025,
    thumb: '/projects/hyrox-koln/thumb.png',
    role: 'Filmmaker',
    logline: 'A team of creators. Hyrox Köln. Shot from the inside.',
    description: 'Coverage of Urban Sports Club\'s sponsorship at Hyrox Köln 2025 — inside the competition with a team of content creators. One of the most physically demanding formats on the circuit, captured from where the effort is impossible to fake. No commentary needed.',
    tags: ['Events', 'Sport', 'Content'],
    template: 'content',
    media: [],
  },

  {
    slug: 'wellhub-the-asset',
    title: 'The Asset',
    client: 'Wellhub',
    category: 'AI',
    categoryColor: CATEGORY_COLORS['AI'],
    format: 'MOCKUMENTARY',
    year: 2026,
    thumb: '/projects/wellhub-the-asset/thumb.png',
    role: 'Production Company',
    logline: 'A journalist investigates the strangest mystery in the corporate world: the employees are thriving.',
    description: 'AI mockumentary for Wellhub. A film that takes the premise seriously enough to be funny — because when workplace wellness actually works, it does look suspicious.',
    tags: ['Video IA', 'Film', 'Brand'],
    template: 'feature',
  },

  {
    slug: 'skyndor-2025',
    title: 'Skyndor',
    client: 'Skyndor',
    category: 'Film',
    categoryColor: CATEGORY_COLORS['Film'],
    format: 'COMMERCIAL',
    year: 2025,
    thumb: '/projects/skyndor-2025/thumb.png',
    thumb2: '/projects/skyndor-2025/thumb2.png',
    role: 'Director / DoP',
    productionCompany: 'Hashtag',
    logline: 'Skincare as ritual. Beauty as precision.',
    description: 'Commercial campaign for Skyndor — a series of beauty films built around the textures, rituals, and results of their facial skincare range. Shot with the precision the product deserved.',
    tags: ['Publicidad', 'Film', 'Beauty'],
    credits: [
      { role: 'Director / DoP', name: 'Sergi Gómez' },
      { role: 'AC', name: 'Georgina Cercós' },
      { role: 'Photographer', name: 'Sergi Jasanada' },
      { role: 'Photo Assist', name: 'Salem Mansour' },
      { role: 'Agency', name: 'Delirium' },
      { role: 'Production Company', name: 'Hashtag' },
    ],
    template: 'content',
    media: [],
  },

  {
    slug: 'bcn-open-2025',
    title: 'BCN Open',
    client: 'BCN Open',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2025,
    thumb: '/projects/bcn-open-2025/thumb.png',
    thumb2: '/projects/bcn-open-2025/thumb2.png',
    role: 'Fotografía',
    logline: 'Court level. Barcelona. ATP 500.',
    description: 'Photography coverage of the BCN Open 2025 — one of the most distinctive tournaments on the clay season. Shot from inside the courts, the corridors, and the crowd.',
    tags: ['Events', 'Photography', 'Sport'],
    template: 'gallery',
    images: [
      '/projects/bcn-open-2025/still-01.png',
      '/projects/bcn-open-2025/still-02.png',
      '/projects/bcn-open-2025/still-03.png',
      '/projects/bcn-open-2025/still-04.png',
      '/projects/bcn-open-2025/still-05.png',
      '/projects/bcn-open-2025/still-06.png',
      '/projects/bcn-open-2025/still-07.png',
      '/projects/bcn-open-2025/still-08.png',
      '/projects/bcn-open-2025/still-09.png',
      '/projects/bcn-open-2025/still-10.png',
      '/projects/bcn-open-2025/still-11.png',
      '/projects/bcn-open-2025/still-12.png',
      '/projects/bcn-open-2025/still-13.png',
      '/projects/bcn-open-2025/still-14.png',
      '/projects/bcn-open-2025/still-15.png',
    ],
  },

  // ─── EVENT PHOTOGRAPHY (only accessible from /events) ───────────────

  {
    slug: 'interparfums-barcelona-2026',
    title: 'Interparfums Barcelona',
    shortTitle: 'Barcelona',
    client: 'Interparfums',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2026,
    thumb: '/projects/interparfums-barcelona/thumb.jpg',
    logline: 'A fragrance brand. Barcelona. The night it all came together.',
    description: 'Event photography for Interparfums in Barcelona 2026. Portraits, atmosphere, and the details that make a room feel like a story.',
    tags: ['Events', 'Photography'],
    template: 'gallery',
    images: [
      '/projects/interparfums-barcelona/still-01.jpg',
      '/projects/interparfums-barcelona/still-02.jpg',
      '/projects/interparfums-barcelona/still-03.jpg',
      '/projects/interparfums-barcelona/still-04.jpg',
      '/projects/interparfums-barcelona/still-05.jpg',
      '/projects/interparfums-barcelona/still-06.jpg',
      '/projects/interparfums-barcelona/still-07.jpg',
      '/projects/interparfums-barcelona/still-08.jpg',
      '/projects/interparfums-barcelona/still-09.jpg',
      '/projects/interparfums-barcelona/still-10.jpg',
      '/projects/interparfums-barcelona/still-11.jpg',
      '/projects/interparfums-barcelona/still-12.jpg',
      '/projects/interparfums-barcelona/still-13.jpg',
      '/projects/interparfums-barcelona/still-14.jpg',
      '/projects/interparfums-barcelona/still-15.jpg',
    ],
    eventOnly: true,
  },

  {
    slug: 'motul-solidarity-gp-2024',
    title: 'Motul Solidarity GP',
    shortTitle: 'Solidarity GP',
    client: 'Motul',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2024,
    thumb: '/projects/motul-solidarity-gp/thumb.jpeg',
    logline: 'Motorsport with a purpose. The GP that gave back.',
    description: 'Event photography at the Motul Solidarity GP 2024. Speed, community, and a weekend that meant something beyond the podium.',
    tags: ['Events', 'Motorsport', 'Photography'],
    template: 'gallery',
    images: [
      '/projects/motul-solidarity-gp/still-01.jpeg',
      '/projects/motul-solidarity-gp/still-02.jpeg',
      '/projects/motul-solidarity-gp/still-03.jpeg',
      '/projects/motul-solidarity-gp/still-04.jpeg',
      '/projects/motul-solidarity-gp/still-05.jpeg',
      '/projects/motul-solidarity-gp/still-06.jpeg',
      '/projects/motul-solidarity-gp/still-07.jpeg',
      '/projects/motul-solidarity-gp/still-08.jpeg',
      '/projects/motul-solidarity-gp/still-09.jpeg',
      '/projects/motul-solidarity-gp/still-10.jpeg',
      '/projects/motul-solidarity-gp/still-11.jpeg',
      '/projects/motul-solidarity-gp/still-12.jpeg',
      '/projects/motul-solidarity-gp/still-13.jpeg',
      '/projects/motul-solidarity-gp/still-14.jpeg',
      '/projects/motul-solidarity-gp/still-15.jpeg',
      '/projects/motul-solidarity-gp/still-16.jpeg',
      '/projects/motul-solidarity-gp/still-17.jpeg',
      '/projects/motul-solidarity-gp/still-18.jpeg',
    ],
    eventOnly: true,
  },

  {
    slug: 'motul-glm-2024',
    title: 'Motul GLM',
    shortTitle: 'GLM',
    client: 'Motul',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2024,
    thumb: '/projects/motul-glm/thumb.jpeg',
    logline: 'Global launch. One room. Every market.',
    description: 'Event photography for Motul GLM 2024 — a global meeting that brought every market into the same space. Architecture, energy, and the people behind the brand.',
    tags: ['Events', 'Photography'],
    template: 'gallery',
    images: [
      '/projects/motul-glm/still-01.jpeg',
      '/projects/motul-glm/still-02.jpeg',
      '/projects/motul-glm/still-03.jpeg',
      '/projects/motul-glm/still-04.jpeg',
      '/projects/motul-glm/still-05.jpeg',
      '/projects/motul-glm/still-06.jpeg',
      '/projects/motul-glm/still-07.jpeg',
      '/projects/motul-glm/still-08.jpeg',
      '/projects/motul-glm/still-09.jpeg',
      '/projects/motul-glm/still-10.jpeg',
      '/projects/motul-glm/still-11.jpeg',
      '/projects/motul-glm/still-12.jpeg',
      '/projects/motul-glm/still-13.jpeg',
      '/projects/motul-glm/still-14.jpeg',
      '/projects/motul-glm/still-15.jpeg',
      '/projects/motul-glm/still-16.jpeg',
      '/projects/motul-glm/still-17.jpeg',
      '/projects/motul-glm/still-18.jpeg',
    ],
    eventOnly: true,
  },

  {
    slug: 'publicis-team-building-2023',
    title: 'Publicis Team Building',
    shortTitle: 'Team Building',
    client: 'Publicis',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2023,
    thumb: '/projects/publicis-team-building/thumb.jpg',
    logline: 'A creative agency, off-brief. The best kind of day.',
    description: 'Event photography for Publicis\'s 2023 team building. The moments that don\'t make it into decks — and the ones that should.',
    tags: ['Events', 'Photography'],
    template: 'gallery',
    images: [
      '/projects/publicis-team-building/still-01.jpg',
      '/projects/publicis-team-building/still-02.jpg',
      '/projects/publicis-team-building/still-03.jpg',
      '/projects/publicis-team-building/still-04.jpg',
      '/projects/publicis-team-building/still-05.jpg',
      '/projects/publicis-team-building/still-06.jpg',
      '/projects/publicis-team-building/still-07.jpg',
      '/projects/publicis-team-building/still-08.jpg',
      '/projects/publicis-team-building/still-09.jpg',
      '/projects/publicis-team-building/still-10.jpg',
      '/projects/publicis-team-building/still-11.jpg',
      '/projects/publicis-team-building/still-12.jpg',
      '/projects/publicis-team-building/still-13.jpg',
      '/projects/publicis-team-building/still-14.jpg',
      '/projects/publicis-team-building/still-15.jpg',
      '/projects/publicis-team-building/still-16.jpg',
      '/projects/publicis-team-building/still-17.jpg',
      '/projects/publicis-team-building/still-18.jpg',
    ],
    eventOnly: true,
  },

  {
    slug: 'honest-greens-barcelona-2020',
    title: 'Honest Greens Barcelona',
    shortTitle: 'Barcelona',
    client: 'Honest Greens',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2020,
    thumb: '/projects/honest-greens-barcelona/thumb.png',
    videoUrl: 'https://www.youtube.com/watch?v=CD_ppiVIRT4',
    logline: 'An opening. A space. Food that actually means something.',
    description: 'Photography and video coverage of the Honest Greens Barcelona opening. A restaurant built around a point of view — and a day that matched it.',
    tags: ['Events', 'Photography'],
    template: 'feature',
    images: [],
    eventOnly: true,
  },

  {
    slug: 'adeslas-team-dinner-2022',
    title: 'Adeslas Team Dinner',
    shortTitle: 'Team Dinner',
    client: 'Adeslas',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2022,
    thumb: '/projects/adeslas-team-dinner/thumb.jpeg',
    logline: 'The dinner nobody wanted to leave.',
    description: 'Event photography for the Adeslas team dinner 2022. Candid portraits, ambient light, and the kind of evening that builds a team without anyone noticing.',
    tags: ['Events', 'Photography'],
    template: 'gallery',
    images: [
      '/projects/adeslas-team-dinner/still-01.jpeg',
      '/projects/adeslas-team-dinner/still-02.jpeg',
      '/projects/adeslas-team-dinner/still-03.jpeg',
      '/projects/adeslas-team-dinner/still-04.jpeg',
      '/projects/adeslas-team-dinner/still-05.jpeg',
      '/projects/adeslas-team-dinner/still-06.jpeg',
      '/projects/adeslas-team-dinner/still-07.jpeg',
      '/projects/adeslas-team-dinner/still-08.jpeg',
      '/projects/adeslas-team-dinner/still-09.jpeg',
      '/projects/adeslas-team-dinner/still-10.jpeg',
      '/projects/adeslas-team-dinner/still-11.jpeg',
      '/projects/adeslas-team-dinner/still-12.jpeg',
      '/projects/adeslas-team-dinner/still-13.jpeg',
      '/projects/adeslas-team-dinner/still-14.jpeg',
      '/projects/adeslas-team-dinner/still-15.jpeg',
      '/projects/adeslas-team-dinner/still-16.jpeg',
      '/projects/adeslas-team-dinner/still-17.jpeg',
      '/projects/adeslas-team-dinner/still-18.jpeg',
    ],
    eventOnly: true,
  },

  {
    slug: 'esmo-2026',
    title: 'ESMO 2026',
    shortTitle: 'ESMO',
    client: 'ESMO',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2026,
    thumb: '/projects/esmo-2026/thumb.png',
    logline: 'Oncology\'s biggest stage. Behind the congress that moves medicine forward.',
    description: 'Making-of photography at ESMO 2026 in Barcelona. Behind the scenes of one of the world\'s leading oncology congresses — the setup, the speakers, the moments between sessions that make a global event feel human.',
    tags: ['Events', 'Photography'],
    template: 'gallery',
    images: [],
    productionCompany: 'OC Studios',
    role: 'Making Of',
    credits: [
      { role: 'Client', name: 'ESMO' },
      { role: 'Agency', name: 'Singular by Plan' },
      { role: 'Production Company', name: 'OC Studios' },
      { role: 'Role', name: 'Making Of' },
    ],
    eventOnly: true,
  },

  {
    slug: 'posidonia-green-fest-2025',
    title: 'Posidonia Green Fest',
    shortTitle: 'Green Fest',
    client: 'Posidonia',
    category: 'Events',
    categoryColor: CATEGORY_COLORS['Events'],
    format: 'EVENT',
    year: 2025,
    thumb: '/projects/posidonia-green-fest/thumb.png',
    logline: 'Art, music, and activism at the edge of the Mediterranean.',
    description: 'Photography at Posidonia Green Festival 2025 — two days at the Museu Marítim de Barcelona dedicated to the sea. A free festival where science meets culture: concerts, talks, workshops, and over 25 organizations working to protect the Mediterranean.',
    tags: ['Events', 'Photography'],
    template: 'gallery',
    images: [],
    eventOnly: true,
  },
];
